import { CopingMechanism } from './types';

export const MOOD_EMOJIS = {
  'very-happy': '😄',
  'happy': '😊',
  'neutral': '😐',
  'sad': '😢',
  'very-sad': '😭',
  'anxious': '😰',
  'angry': '😠',
  'excited': '🤩',
} as const;

export const MOOD_LABELS = {
  'very-happy': 'Very Happy',
  'happy': 'Happy',
  'neutral': 'Neutral',
  'sad': 'Sad',
  'very-sad': 'Very Sad',
  'anxious': 'Anxious',
  'angry': 'Angry',
  'excited': 'Excited',
} as const;

export const COPING_MECHANISMS: CopingMechanism[] = [
  {
    id: '1',
    name: '4-7-8 Breathing',
    description: 'A calming breathing technique to reduce anxiety',
    type: 'breathing',
    content: 'Inhale for 4 counts, hold for 7 counts, exhale for 8 counts. Repeat 3-4 times.',
    duration: 2,
    difficulty: 'easy',
    tags: ['anxiety', 'stress', 'quick'],
    isPremium: false,
  },
  {
    id: '2',
    name: 'Gratitude Reflection',
    description: 'Focus on three things you\'re grateful for today',
    type: 'mindfulness',
    content: 'Take a moment to think of three specific things you\'re grateful for today. Write them down or say them aloud.',
    duration: 3,
    difficulty: 'easy',
    tags: ['gratitude', 'positivity', 'mindfulness'],
    isPremium: false,
  },
  {
    id: '3',
    name: 'Positive Affirmation',
    description: 'Boost your confidence with self-affirming statements',
    type: 'affirmation',
    content: 'Repeat: "I am capable, I am strong, I can handle whatever comes my way." Say it with conviction.',
    duration: 1,
    difficulty: 'easy',
    tags: ['confidence', 'self-esteem', 'quick'],
    isPremium: false,
  },
  {
    id: '4',
    name: '5-Minute Walk',
    description: 'Get moving to boost your mood naturally',
    type: 'movement',
    content: 'Take a 5-minute walk, preferably outside. Focus on your surroundings and breathe deeply.',
    duration: 5,
    difficulty: 'easy',
    tags: ['exercise', 'nature', 'mood-boost'],
    isPremium: false,
  },
  {
    id: '5',
    name: 'Mindful Journaling',
    description: 'Express yourself through guided writing',
    type: 'journaling',
    content: 'Write about your current feelings without judgment. Ask yourself: What am I feeling? Why might I feel this way? What do I need right now?',
    duration: 5,
    difficulty: 'medium',
    tags: ['self-reflection', 'emotions', 'writing'],
    isPremium: false,
  },
  {
    id: '6',
    name: 'Body Scan Meditation',
    description: 'Release tension through mindful awareness',
    type: 'mindfulness',
    content: 'Lie down and mentally scan your body from head to toe. Notice any tension and consciously relax those areas.',
    duration: 10,
    difficulty: 'medium',
    tags: ['relaxation', 'meditation', 'body-awareness'],
    isPremium: true,
  },
  {
    id: '7',
    name: 'Progressive Muscle Relaxation',
    description: 'Systematically tense and relax muscle groups',
    type: 'movement',
    content: 'Starting with your toes, tense each muscle group for 5 seconds, then relax. Work your way up to your head.',
    duration: 15,
    difficulty: 'medium',
    tags: ['relaxation', 'tension-relief', 'physical'],
    isPremium: true,
  },
  {
    id: '8',
    name: 'Loving-Kindness Meditation',
    description: 'Cultivate compassion for yourself and others',
    type: 'mindfulness',
    content: 'Send loving thoughts to yourself, then to loved ones, neutral people, difficult people, and all beings.',
    duration: 12,
    difficulty: 'medium',
    tags: ['compassion', 'meditation', 'relationships'],
    isPremium: true,
  },
  {
    id: '9',
    name: 'Visualization Exercise',
    description: 'Create a mental safe space for calm and peace',
    type: 'visualization',
    content: 'Close your eyes and imagine a peaceful place. Engage all your senses - what do you see, hear, smell, and feel?',
    duration: 8,
    difficulty: 'medium',
    tags: ['imagination', 'calm', 'mental-imagery'],
    isPremium: true,
  },
  {
    id: '10',
    name: 'Quick Energy Boost',
    description: 'Simple movements to increase energy and mood',
    type: 'movement',
    content: 'Do 10 jumping jacks, 5 push-ups, and stretch your arms overhead. Focus on how your body feels.',
    duration: 3,
    difficulty: 'easy',
    tags: ['energy', 'exercise', 'quick'],
    isPremium: false,
  },
];

export const COMMON_TRIGGERS = [
  'Work stress',
  'Relationship issues',
  'Financial concerns',
  'Health worries',
  'Social situations',
  'Family dynamics',
  'Sleep issues',
  'Weather',
  'News/media',
  'Technology problems',
];
