import { CopingMechanism } from './types';

export const MOOD_EMOJIS = {
  'happy': '😊',
  'sad': '😢',
  'anxious': '😰',
  'angry': '😠',
  'excited': '🤩',
  'calm': '😌',
  'frustrated': '😤',
  'grateful': '🙏',
  'overwhelmed': '😵',
  'content': '😊',
} as const;

export const MOOD_LABELS = {
  'happy': 'Happy',
  'sad': 'Sad',
  'anxious': 'Anxious',
  'angry': 'Angry',
  'excited': 'Excited',
  'calm': 'Calm',
  'frustrated': 'Frustrated',
  'grateful': 'Grateful',
  'overwhelmed': 'Overwhelmed',
  'content': 'Content',
} as const;

export const COPING_MECHANISMS: CopingMechanism[] = [
  {
    id: '1',
    name: '4-7-8 Breathing',
    description: 'A calming breathing technique to reduce anxiety',
    type: 'breathing',
    content: 'Inhale for 4 counts, hold for 7 counts, exhale for 8 counts. Repeat 3-4 times.',
    duration: 2,
    difficulty: 'easy',
    tags: ['anxiety', 'stress', 'sleep'],
    isPremium: false,
  },
  {
    id: '2',
    name: 'Gratitude Reflection',
    description: 'Focus on three things you\'re grateful for today',
    type: 'mindfulness',
    content: 'Take a moment to think of three specific things you\'re grateful for today. Write them down or say them aloud.',
    duration: 3,
    difficulty: 'easy',
    tags: ['gratitude', 'positivity', 'reflection'],
    isPremium: false,
  },
  {
    id: '3',
    name: 'Positive Affirmation',
    description: 'Boost your confidence with self-affirming statements',
    type: 'affirmation',
    content: 'Repeat: "I am capable, I am strong, I can handle whatever comes my way." Say it with conviction.',
    duration: 1,
    difficulty: 'easy',
    tags: ['confidence', 'self-esteem', 'motivation'],
    isPremium: false,
  },
  {
    id: '4',
    name: '5-Minute Walk',
    description: 'Get moving to boost your mood naturally',
    type: 'movement',
    content: 'Take a 5-minute walk, preferably outside. Focus on your surroundings and breathe deeply.',
    duration: 5,
    difficulty: 'easy',
    tags: ['exercise', 'mood', 'energy'],
    isPremium: false,
  },
  {
    id: '5',
    name: 'Visualization Exercise',
    description: 'Create a peaceful mental image',
    type: 'visualization',
    content: 'Close your eyes and imagine a peaceful place. Engage all your senses - what do you see, hear, smell, and feel?',
    duration: 5,
    difficulty: 'easy',
    tags: ['relaxation', 'stress', 'calm'],
    isPremium: false,
  },
  {
    id: '6',
    name: 'Body Scan Meditation',
    description: 'Release tension through mindful awareness',
    type: 'mindfulness',
    content: 'Lie down and mentally scan your body from head to toe. Notice any tension and consciously relax those areas.',
    duration: 10,
    difficulty: 'medium',
    tags: ['stress', 'tension', 'relaxation'],
    isPremium: true,
  },
  {
    id: '7',
    name: 'Emotional Journaling',
    description: 'Process your feelings through writing',
    type: 'journaling',
    content: 'Write about what you\'re feeling right now. Don\'t worry about grammar or structure - just let your thoughts flow onto paper.',
    duration: 10,
    difficulty: 'easy',
    tags: ['processing', 'emotions', 'clarity'],
    isPremium: false,
  },
  {
    id: '8',
    name: 'Progressive Muscle Relaxation',
    description: 'Systematically relax your entire body',
    type: 'movement',
    content: 'Starting with your toes, tense each muscle group for 5 seconds, then release. Work your way up to your head.',
    duration: 15,
    difficulty: 'medium',
    tags: ['tension', 'relaxation', 'physical'],
    isPremium: true,
  },
  {
    id: '9',
    name: 'Safe Place Visualization',
    description: 'Create a mental sanctuary for peace',
    type: 'visualization',
    content: 'Imagine a place where you feel completely safe and calm. Engage all your senses - what do you see, hear, smell, and feel in this space?',
    duration: 8,
    difficulty: 'easy',
    tags: ['safety', 'calm', 'peace'],
    isPremium: true,
  },
  {
    id: '10',
    name: 'Box Breathing',
    description: 'Four-count breathing for instant calm',
    type: 'breathing',
    content: 'Breathe in for 4 counts, hold for 4, exhale for 4, hold empty for 4. Repeat this square pattern 5-10 times.',
    duration: 3,
    difficulty: 'easy',
    tags: ['anxiety', 'focus', 'calm'],
    isPremium: false,
  },
];

export const COMMON_TRIGGERS = [
  'Work stress',
  'Relationship issues',
  'Financial concerns',
  'Health worries',
  'Social situations',
  'Family dynamics',
  'Sleep issues',
  'Weather',
  'News/media',
  'Technology problems',
];
